apiVersion: v1
kind: ServiceAccount
metadata:
  name: guestbook-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-operator
spec:
  selector:
    matchLabels:
      app: guestbook-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook-operator
    spec:
      serviceAccountName: guestbook-operator
      containers:
        - name: guestbook-operator
          image: yu3papa/guestbook-operator:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guestbook-operator-admin
subjects:
  - kind: ServiceAccount
    name: guestbook-operator
    namespace: my-operator
roleRef:
  kind: ClusterRole
  name: guestbook-operator
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guestbook-operator
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "apps"
    resources:
      - deployments
      - services
      - pods
      - pods/exec
    verbs:
      - '*'
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "com.jadecross"
    resources:
      - guestbooks
    verbs:
      - '*'